### ISSUE TITLE
[feat] 유저 정보 관련 로직 설계 및 구현

### ISSUE THREAD

**Issue by junchanpp** [Team-Crops/fit-server#20]
## 🍠 Feature Issue

- 마이페이지에서 유저 정보 수정관련 api 설계 및 구현
- 기술, 포지션에 관련한 로직 설계 및 구현
- 학교 자동완성을 위한 db 구축
- pdf 업로드를 위한 로직. pdf 업로드 시 presigned-url에 temp에 임시 저장(1일)해두고, 실제로 서버에 해당 주소가 등록되었을 때 원래 저장소로 이동하게 해야 할 거 같음.(의미없는 데이터가 쌓이는 것을 방지)

## ✅ To-do

- [ ] 유저 필수 정보 입력
- [ ] 유저 선택 정보 입력
- [x] 지역 관련 db 입력
- [x] 학교 관련 db 입력 및 get api 구현
- [x] 기술 및 포지션 로직 구현
- [ ] pdf 업로드 시 임시저장 로직 구현
