### ISSUE TITLE
[feat, test] Test Code 작성하기, 명세서 작성하기, 400 에러 메세지 상세

### ISSUE THREAD

**Issue by SeorinY** [Team-Crops/fit-server#24]
## 🍠 Feature Issue

- chat, oauth login  test code 작성하기
- spring rest docs + swagger 명세서 작성하기
- 에러 메세지 구체화 하기
- Oauth HTTP Method 변경하기

## ✅ To-do

- [x] chat, oauth login  test code 작성하기
- [x] spring rest docs + swagger 명세서 작성하기
- [x]  에러 메세지 구체화 하기
- [x] Oauth HTTP Method 변경하기
