### ISSUE TITLE
[feat] patch에서 null도 초기화할 수 있게 수정

### ISSUE THREAD

**Issue by junchanpp** [Team-Crops/fit-server#31]
## 🍠 Feature Issue

- patch에서 null도 초기화할 수 있게 수정

## ✅ To-do

- [x] patch에서 null도 초기화할 수 있게 수정
- [x] 기존 patch 메서드에서 JsonNullable 참고하게 수정
- [x] 기존 put만 있던 도메인에서 patch 추가

**Comment by junchanpp** [comment]
https://velog.io/@9pruruluru2/Spring에서-json에서-정의되지-않은-필드를-처리하는-방법

해당 이슈에 대해 글도 써보았습니당
