### ISSUE TITLE
[feat] 팀원 추천 도메인 TDD

### ISSUE THREAD

**Issue by SeorinY** [Team-Crops/fit-server#39]
## 🍠 Feature Issue

- 팀원 추천 api 추가
- 채팅 서버 추가 작업 관련 이슈

## ✅ To-do

- [ ] 팀원 추천 api 생성
- [ ] 채팅 데이터 몽고디비에 저장
- [ ] 최근 채팅 불러오기 api 추가

**Comment by junchanpp** [comment]
팀원 추천 api와 채팅은 다른 도메인이어서 분리하는 게 좋을 것 같습니다.
