### ISSUE TITLE
[feat] 내 프로젝트 로직 구현

### ISSUE THREAD

**Issue by junchanpp** [Team-Crops/fit-server#44]
## 🍠 Feature Issue

- 매칭이 완료되어 프로젝트 진행 중/진행 완료된 프로젝트 구현
## ✅ To-do

- [x] 프로젝트 목록 조회 api 구현
- [x] 프로젝트 완료 api 구현
- [x] 프로젝트 이름 수정 api 구현
