### ISSUE TITLE
[feat] position 영문 이름 컬럼 추가

### ISSUE THREAD

**Issue by junchanpp** [Team-Crops/fit-server#51]
## 🍠 Feature Issue

- position 영문 이름 컬럼 추가
- positionType 생성 api 에 추가
- positionType, imageUrl 조회 api에 추가

## ✅ To-do

- [x] position 영문 이름 컬럼 추가
- [x] positionType 생성 api 에 추가
- [x] positionType, imageUrl 조회 api에 추가

**Comment by junchanpp** [comment]
#44 merge 후 PR 생성 예정
