### ISSUE TITLE
[feat] 미작성한 테스트 코드 추가 및 기존 테스트 코드 리펙터링

### ISSUE THREAD

**Issue by junchanpp** [Team-Crops/fit-server#59]
## 🍠 Feature Issue

- 매칭 도메인 테스트 코드 추가
- 신고하기 관련 로직 테스트 코드 추가
- 프로젝트 관련 테스트 코드 추가
- 기존 테스트 코드 리펙터링

## ✅ To-do

- [x] 매칭 도메인 테스트 코드 추가
- [x] 신고하기 관련 로직 테스트 코드 추가
- [x] 프로젝트 관련 테스트 코드 추가
- [ ] 기존 테스트 코드 리펙터링
