### ISSUE TITLE
[feat] CI/CD Pipeline

### ISSUE THREAD

**Issue by SeorinY** [Team-Crops/fit-server#6]
## 🍠 Feature Issue

- Githuc Actions 파일 추가
- Docker파일 추가

## ✅ To-do

- [x] CI 용 Github Actions 파일 추가
- [x] CD 용 Github Actions 파일 추가 - Dev
- [x] Docker파일 추가
- [x] Aws Code Deploy, Ecr 사용
- [x] rmi 스크립트 추가
- [x] pr 시 테스트 결과 추가
- [ ] cd 파이프라인 트리거 pull request 삭제
- [ ] docker compose db, redis 확인 및 실행 로직 추가
